# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mmu_social' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  # Pods for mmu_social

  target 'mmu_socialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mmu_social-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mmu_social-tvOS

end
